Update for v4 to get provider plugin working.
jakeFeldman/strapi-provider-upload-azure-storage pull request #31
Opened 2021-11-30 20:17 UTC by xanderakafonz

- Change for readme given new config object required on provider https://github.com/strapi/strapi/pull/11731
- Change for blob config (unsure if this is an issue with my azure setup, but isnt an issue on V3, breaks on V4)
Thanks to derrickmehaffy@strapi for support

2021-12-03 08:20 UTC, jakeFeldman requested changes
Hello and thank you for the PR! I'm glad the to see the upgrade path from v3 -> v4 is minor.

The if/else logic is not needed. Once thats updated, I'd be happy to merge this in and get a new version published.

Thanks again!

2021-12-03 08:20 UTC, jakeFeldman commented on lib/index.js
> +                }
This is unneeded. The ternary already handles this check.

2021-12-05 20:30 UTC, jakeFeldman commented
Thanks for the PR again. I pushed the README changes and published a new version so npm is up to date as well. Going to close this for now. If you're still having an issue with the `cdnBaseUrl` please let me know and file an issue. Thanks again and good luck!

2021-12-05 20:30 UTC, closed without merging

2021-12-05 20:48 UTC, Webbist-dev commented
Cheers, Jake! Got it all working before I issued a PR - issue with CDN was I had it populated but not setup in azure properly *facepalm*

2021-12-05 20:53 UTC, jakeFeldman commented
Awesome to hear! Thanks again!